### ISSUE TITLE
doc file make failed

### ISSUE THREAD

**Issue by ShawnHSH** [elliothe/pytorx#1]
When I tried "make html" under the doc directory, it turns out many "no module named" warnings and "no title" warnings.  My Sphinx version is v4.1.2, and my python version is 3.6.8. Could you please help me to figure it out?

/home/harold/pytorx-alpha/doc/source/index.rst:15: WARNING: toctree contains reference to nonexisting document 'introduction/know_issue'
/home/harold/pytorx-alpha/doc/source/index.rst:15: WARNING: toctree contains reference to nonexisting document 'introduction/support'
WARNING: autodoc: failed to import module 'demo1'; the following exception was raised:
No module named 'demo1'
WARNING: autodoc: failed to import module 'demo2'; the following exception was raised:
No module named 'demo2'
WARNING: autodoc: failed to import module 'crxb_solver'; the following exception was raised:
No module named 'crxb_solver'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] pack_ref/layer                                         
/home/harold/pytorx-alpha/doc/source/index.rst:29: WARNING: toctree contains reference to document 'notes/bug' that doesn't have a title: no link will be generated
/home/harold/pytorx-alpha/doc/source/index.rst:29: WARNING: toctree contains reference to document 'notes/bug' that doesn't have a title: no link will be generated
/home/harold/pytorx-alpha/doc/source/index.rst:29: WARNING: toctree contains reference to document 'notes/bug' that doesn't have a title: no link will be generated
generating indices... genindex /home/harold/pytorx-alpha/doc/source/index.rst:29: WARNING: toctree contains reference to document 'notes/bug' that doesn't have a title: no link will be generated
done
writing additional pages... search /home/harold/pytorx-alpha/doc/source/index.rst:29: WARNING: toctree contains reference to document 'notes/bug' that doesn't have a title: no link will be generated
done

**Comment by elliothe** [comment]
Sorry. When posting the code, I did not maintain the doc at the end.
