### ISSUE TITLE
crxb.sp netlist access

### ISSUE THREAD

**Issue by LGB7** [elliothe/pytorx#2]
Hello,
I just wanted to ask you regarding the crxb.sp where is it being called or accessed in codes? Is the mnist.py file in the benchmark accessing the results of the simulation in some way? Because I can't seem to find a relationship between the netlist and the .py files.

Thank you for your help

**Comment by elliothe** [comment]
that spice is to validate the correctness of our code using modified nodal analysis to compute IR drop. We did not write a script to cross-check the computed result, instead, we did that manually.

> Hello, I just wanted to ask you regarding the crxb.sp where is it being called or accessed in codes? Is the mnist.py file in the benchmark accessing the results of the simulation in some way? Because I can't seem to find a relationship between the netlist and the .py files.
> 
> Thank you for your help
